### ISSUE TITLE
Ballot#112 John Moehrke, By Light Professional IT Services | From: Apps should persist tokens and other sensitive data in app-specific storage loca...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#116] opened 2017-12-21 21:16 UTC
### Ballot Weight
A-Q

### Where
SMART authorization and resource retrieval :: /

### What
John Moehrke, By Light Professional IT Services
From: Apps should persist tokens and other sensitive data in app-specific storage locations only, not in system-wide-discoverable locations.
Comment: This wordng makes obvious sense for web applications, but is not so obvious for native applications - what does it actually imply?

### Josh's Triage Notes
(See same commnet from Grahame)

### Disposition
Persuasive with mod

"Apps should persist tokens and other sensitive data in app-specific storage locations only, not in system-wide-discoverable locations." -> Apps should not persist tokens and other sensitive data in a way that allows unauthorized access.

### Vote Details
Pro-Con-Abstain: 8-0-0
Date: 2017-10-26

**Comment by Healthedata1** [comment] 2018-05-10 03:55
dupe of Ballot#43, #47

**Closed** 2018-07-17 03:53 UTC
Labels: ballot-2017, duplicate, ready-to-apply
