### ISSUE TITLE
Ballot#179 Kensaku Kawamoto, MD, PhD, MHS, University of Utah | Some contracted words (e.g., can' t) have extra spacing after the apostrophe visual...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#176] opened 2017-12-21 21:18 UTC
### Ballot Weight
A-T

### Where
General :: http://www.hl7.org/fhir/smart-app-launch/

### What
Kensaku Kawamoto, MD, PhD, MHS, University of Utah
Comment: Some contracted words (e.g., can' t) have extra spacing after the apostrophe visually (though not there in text), when viewed on Chrome.  May want to see if can get this to look right.  May be an issue on other pages.
Summary: HTML formatting?

### Josh's Triage Notes
Merge with theme: "Publication Format"

### Disposition
See disposition for Theme "Publication Format"

### Vote Details
Pro-Con-Abstain: 
Date:

**Comment by Healthedata1** [comment] 2017-12-27 22:36
applied this is duplicate of #41

**Comment by jmandel** [comment] 2017-12-27 22:50
For links to ballot issues, can you write `Ballot#41` to  avoid confusion with the auto-generated GitHub issue links?

**Comment by Healthedata1** [comment] 2017-12-27 23:02
For commits only referenced github issues.  Which ones should I reference?
i've only been updating the Git issues.

Eric

Eric M Haas, DVM, MS
Health eData Inc
601 Monroe Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com

**Closed** 2018-05-10 06:18 UTC
Labels: applied, ballot-2017, ready-to-apply
